import { createFileRoute, Link } from "@tanstack/react-router";

const title = "Terms & Conditions — Greta Rusecke";
const description =
  "Terms of use for Greta Rusecke's portfolio site, including the Greta AI assistant and contact form.";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title },
      { name: "description", content: description },
      { property: "og:title", content: title },
      { property: "og:description", content: description },
      { property: "og:type", content: "article" },
      { name: "twitter:card", content: "summary" },
      { name: "robots", content: "noindex" },
    ],
    links: [{ rel: "canonical", href: "/terms" }],
  }),
  component: Terms,
});

function Terms() {
  return (
    <main className="mx-auto max-w-3xl px-5 py-20">
      <Link to="/" className="font-mono text-xs uppercase tracking-[0.2em] text-primary">
        ← Back to portfolio
      </Link>
      <h1 className="mt-6 text-4xl font-bold">Terms &amp; Conditions</h1>
      <p className="mt-2 text-sm text-muted-foreground">Last updated: 5 August 2026</p>

      <div className="mt-10 space-y-8 text-sm leading-relaxed text-muted-foreground">
        <section>
          <h2 className="text-lg font-semibold text-foreground">1. Purpose of this site</h2>
          <p className="mt-2">
            This website presents the professional background, skills and projects of Greta Rusecke.
            It is informational and does not constitute a service offer or contract.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">2. Greta AI assistant</h2>
          <p className="mt-2">
            The "Greta AI" assistant is an automated tool that answers questions about Greta's
            career only. Its answers are generated by an AI model and may contain inaccuracies; they
            are not binding statements. Do not submit confidential or personal information through
            the chat.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">3. Intellectual property</h2>
          <p className="mt-2">
            The content, design, text and images on this site belong to Greta Rusecke unless stated
            otherwise. Reuse without written permission is not allowed. Third-party project links
            remain the property of their respective owners.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">4. External links</h2>
          <p className="mt-2">
            Links to external sites (GitHub, LinkedIn, client projects) are provided for convenience.
            No responsibility is taken for their content or availability.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">5. Acceptable use</h2>
          <p className="mt-2">
            You agree not to misuse the contact form or chat for spam, abusive content, automated
            scraping, or attempts to disrupt the service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">6. Liability</h2>
          <p className="mt-2">
            The site is provided "as is" without warranties. Greta Rusecke is not liable for any
            damage arising from its use.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">7. Governing law</h2>
          <p className="mt-2">These terms are governed by the laws of Greece.</p>
        </section>
      </div>
    </main>
  );
}
